### ISSUE TITLE
Switch to use `colorsGen`

### ISSUE THREAD

**Issue by barracuda156** [stla/RCDT#2]
Could we switch this to use your `colorsGen` too?

**Comment by stla** [comment]
That is done.

```r
remotes::install_github("stla/RCDT", dependencies = TRUE, build_vignettes = TRUE)
```
or wait for the CRAN version.

**Comment by stla** [comment]
On CRAN now.

**Comment by barracuda156** [comment]
Thank you!

I have added it to Macports too: 
https://ports.macports.org/port/R-RCDT
