### ISSUE TITLE
voronoi tesselation

### ISSUE THREAD

**Issue by Huimin721** [stla/RCDT#3]
Dear authors,

Thanks so much for creating the outstanding package. As the triangulation has been implemented, could I ask if the fast algorithm can be genralized to voronoi tesselation as well?

**Comment by stla** [comment]
Hello,

The RCDT package is built on the top of the C++ library CDT, which does not provide the Voronoï tessellation. You can use the R packages **deldir**, **sf** or **tessellation**.

**Comment by Huimin721** [comment]
@stla Thanks so much! Could I confirm if every two dots connected by some edge in the Delaunay network generated by RCDT are sharing a common border in the corresponding voronoi diagram? i.e. the result of RCDT is a duality of the voronoi diagram?

**Comment by Huimin721** [comment]
@stla Sorry for being not clear. I mean, would it be possible to generate a Voronoi diagram from a Delaunay triangulation produced by the RCDT algorithm? Considering that RCDT is the fastest Delaunay implementation, I am seeking an algorithm that could provide Voronoi tessellation based on the triangulation network. Any guidance on this would be greatly appreciated. Thanks so much!

**Comment by stla** [comment]
Hello,

Yes, this is possible, but this is not a straightforward task. And I don't know whether RCDT is the fastest Delaunay implementation, I didn't compare with **deldir** or **sf**.

**Comment by stla** [comment]
And **deldir** and **sf** have nice features for the Voronoï diagram, e.g. you can clip it to a rectangle or something else.

**Comment by Huimin721** [comment]
@stla Thanks so much for the reply! I have compared it with deldir and df, RCDT is like super fast as a dream. Could I ask if it is possible to have further update about Voronoi in RCDT?

**Comment by stla** [comment]
I don't think so. I already implemented the Voronoï diagram in my package **tessellation**. It is fast too and it can perform 3D Delaunay/Voronoï tessellations as well. And **deldir** and **sf** are very good packages, the speed is not the only concern.

**Comment by Huimin721** [comment]
@stla OK, thanks for letting me know! I will check tessellation. Really appreciate for your implementation of RCDT!
